version: '3'
services:
  api:
    build: .
    container_name: clean-node-api
    image: clean-node-api
    restart: always
    ports:
      - '5050:5050'
    depends_on:
      - database
#      - redis
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
  
  #cache:
  #  image: redis:alpine
  #  command: ["redis-server", "--bind", "redis", "--port", "6379"]

  database:
    image: mongo:3
    restart: always
    volumes:
      - ./mongoDB_data:/data
    ports:
      - "27017:27017"
