version: '3'
services:
  api:
    container_name: clean-node-api
    build: .
  
    restart: always
    ports:
      - '5050:5050'
      - '9222:9222'
    depends_on:
      - database
#      - redis
    command: bash -c "npm install --omit=dev && npm run debug"
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    environment:
      - MONGO_URL=mongodb://database:27017/clean-node-api
  
  #cache:
  #  image: redis:alpine
  #  command: ["redis-server", "--bind", "redis", "--port", "6379"]

  database:
    image: mongo:3
    restart: always
    volumes:
      - ./mongoDB_data:/data
    ports:
      - "27017:27017"
